// ============================================================================
// PLANO DE CONTAS — as mesmas 292 contas do sistema original (HTML/localStorage),
// extraídas em 02/08/2026 durante a migração para React + Firebase (Fase 2).
// Único e compartilhado por todas as empresas cadastradas — não é editável pela
// interface, pois é a base curricular do curso.
// ============================================================================

export const CONTAS = [
  { codigo: "1", nome: "ATIVO", nivel: 1, grupo: "Ativo", tipo: "Grupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.1", nome: "ATIVO CIRCULANTE", nivel: 2, grupo: "Ativo", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.1.1", nome: "Caixa e Equivalentes de Caixa", nivel: 3, grupo: "Ativo", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.1.1.01", nome: "Caixa Geral", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.1.02", nome: "Bancos Conta Movimento", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.1.1.02.01", nome: "Banco X", nivel: 5, grupo: "Ativo", tipo: "Subconta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.1.02.02", nome: "Banco Y", nivel: 5, grupo: "Ativo", tipo: "Subconta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.1.03", nome: "Aplicações de Liquidez Imediata", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.1.1.03.01", nome: "Aplicação Banco X", nivel: 5, grupo: "Ativo", tipo: "Subconta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.1.03.02", nome: "Aplicação Banco Y", nivel: 5, grupo: "Ativo", tipo: "Subconta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.1.04", nome: "Cheques em Cobrança", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.1.05", nome: "Numerários em Trânsito", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.1.06", nome: "Caixa Filial", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.1.07", nome: "Fundo Fixo de Caixa", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2", nome: "Valores a Receber", nivel: 3, grupo: "Ativo", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.1.2.01", nome: "Duplicatas a Receber", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.02", nome: "Clientes", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.03", nome: "Notas Promissórias", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.04", nome: "Cartões de Crédito a Receber", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.05", nome: "Cheques a Receber", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.06", nome: "Adiantamento a Fornecedores", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.07", nome: "Adiantamento a Empregados", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.08", nome: "Empréstimos a Coligadas (CP)", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.09", nome: "Juros a Receber", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.10", nome: "Aluguéis a Receber", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.11", nome: "ICMS a Recuperar", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.12", nome: "ICMS-ST a Recuperar", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.13", nome: "IPI a Recuperar", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.14", nome: "PIS a Recuperar", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.15", nome: "COFINS a Recuperar", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.16", nome: "IRRF a Compensar", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.17", nome: "Adiantamento a Sócios", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.18", nome: "Dividendos a Receber", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.19", nome: "Juros sobre Capital Próprio a Receber", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.2.99", nome: "(-) Provisão para Créditos de Liquidação Duvidosa", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "1.1.3", nome: "Estoques", nivel: 3, grupo: "Ativo", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.1.3.01", nome: "Mercadorias para Revenda", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.02", nome: "Mercadorias em Trânsito", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.03", nome: "Mercadorias em Poder de Terceiros", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.04", nome: "Matérias-Primas", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.05", nome: "Material Secundário", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.06", nome: "Produtos em Elaboração", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.07", nome: "Produtos Acabados", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.08", nome: "Material de Expediente", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.09", nome: "Serviços em Andamento", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.10", nome: "Material de Consumo", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.11", nome: "Embalagens", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.12", nome: "Almoxarifado", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.3.99", nome: "(-) Perdas / Ajuste de Estoques", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "1.1.4", nome: "Despesas Antecipadas", nivel: 3, grupo: "Ativo", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.1.4.01", nome: "Seguros a Apropriar", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.4.02", nome: "Assinaturas e Licenças", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.1.4.03", nome: "Aluguéis Antecipados", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2", nome: "ATIVO NÃO CIRCULANTE", nivel: 2, grupo: "Ativo", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.2.1", nome: "Realizável a Longo Prazo", nivel: 3, grupo: "Ativo", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.2.1.01", nome: "Clientes LP", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.1.02", nome: "Títulos a Receber", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.1.03", nome: "Depósitos Judiciais", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.1.04", nome: "Empréstimos a Coligadas", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.1.05", nome: "Tributos Diferidos", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.2", nome: "Investimentos", nivel: 3, grupo: "Ativo", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.2.2.01", nome: "Ações de Controladas", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.2.02", nome: "Ações de Coligadas", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.2.03", nome: "Outras Participações", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3", nome: "Imobilizado", nivel: 3, grupo: "Ativo", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.2.3.01", nome: "Edificações", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.02", nome: "Móveis e Utensílios", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.03", nome: "Veículos", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.04", nome: "Ferramentas", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.05", nome: "Máquinas e Equipamentos", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.06", nome: "Reflorestamentos", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.07", nome: "Equipamentos de Informática", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.08", nome: "Instalações", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.09", nome: "Terrenos", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.3.51", nome: "(-) Depreciação Acumulada Edificações", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "1.2.3.52", nome: "(-) Depreciação Acumulada Móveis", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "1.2.3.53", nome: "(-) Depreciação Acumulada Veículos", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "1.2.3.54", nome: "(-) Depreciação Acumulada Ferramentas", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "1.2.3.55", nome: "(-) Depreciação Acumulada Máquinas", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "1.2.3.56", nome: "(-) Exaustão Acumulada", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "1.2.4", nome: "Intangível", nivel: 3, grupo: "Ativo", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "1.2.4.01", nome: "Fundo de Comércio", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.4.02", nome: "Marcas e Patentes", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.4.03", nome: "Softwares", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.4.04", nome: "Direitos Autorais", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.4.05", nome: "Licenças", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "1.2.4.99", nome: "(-) Amortização Acumulada", nivel: 4, grupo: "Ativo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2", nome: "PASSIVO", nivel: 1, grupo: "Passivo", tipo: "Grupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1", nome: "PASSIVO CIRCULANTE", nivel: 2, grupo: "Passivo", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.1", nome: "Fornecedores", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.1.01", nome: "Duplicatas a Pagar", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.1.02", nome: "Fornecedores Diversos", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.2", nome: "Contas a Pagar", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.2.01", nome: "Convênios a Pagar", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.2.02", nome: "Plano de Saúde Funcionários", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.3", nome: "Obrigações Trabalhistas", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.3.01", nome: "Salários a Pagar", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.3.02", nome: "Pró-Labore a Pagar", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.3.03", nome: "Férias a Pagar", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.3.04", nome: "13º Salário a Pagar", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.4", nome: "Encargos Sociais", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.4.01", nome: "INSS Folha", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.4.02", nome: "INSS Retido PJ", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.4.03", nome: "FGTS a Recolher", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.5", nome: "Provisão de Férias", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.5.01", nome: "Provisão de Férias", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.5.02", nome: "Encargos sobre Férias", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.6", nome: "Provisão 13º Salário", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.6.01", nome: "Provisão 13º", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.6.02", nome: "Encargos 13º", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.7", nome: "Dividendos", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.7.01", nome: "Dividendos a Pagar", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.7.02", nome: "Dividendos Intermediários", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8", nome: "Tributos a Recolher", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.8.01", nome: "IRPJ", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.02", nome: "CSLL", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.03", nome: "IPI", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.04", nome: "ICMS", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.05", nome: "PIS", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.06", nome: "COFINS", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.07", nome: "PIS Importação", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.08", nome: "COFINS Importação", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.09", nome: "ISS", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.10", nome: "IRRF a Recolher", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.11", nome: "INSS Retido Empregados", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.8.12", nome: "Simples Nacional a Recolher", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.9", nome: "Empréstimos e Financiamentos", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.9.01", nome: "Empréstimos Bancários", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.9.02", nome: "Financiamentos", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.9.99", nome: "(-) Encargos a Transcorrer", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "2.1.10", nome: "Desconto de Duplicatas", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.1.10.01", nome: "Duplicatas Descontadas", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.1.10.99", nome: "(-) Encargos", nivel: 4, grupo: "Passivo", tipo: "Conta Analítica", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "2.2", nome: "PASSIVO NÃO CIRCULANTE", nivel: 2, grupo: "Passivo", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "2.2.1", nome: "Adiantamento de Sócios", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.2.2", nome: "Adiantamento de Acionistas", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.2.3", nome: "Empréstimos de Coligadas", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "2.2.4", nome: "Empréstimos de Controladas", nivel: 3, grupo: "Passivo", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3", nome: "PATRIMÔNIO LÍQUIDO", nivel: 1, grupo: "Patrimônio Líquido", tipo: "Grupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "3.1", nome: "Capital Social", nivel: 2, grupo: "Patrimônio Líquido", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "3.1.01", nome: "Capital Subscrito", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.1.02", nome: "(-) Capital a Integralizar", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "3.2", nome: "Reservas de Capital", nivel: 2, grupo: "Patrimônio Líquido", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "3.2.01", nome: "Ágio na Emissão", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.2.02", nome: "Doações/Subvenções", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.2.03", nome: "Prêmios Debêntures", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.3", nome: "Ajustes de Avaliação", nivel: 2, grupo: "Patrimônio Líquido", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "3.3.01", nome: "Ativos", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.3.02", nome: "Passivos", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.4", nome: "Reservas de Lucros", nivel: 2, grupo: "Patrimônio Líquido", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "3.4.01", nome: "Reserva Legal", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.4.02", nome: "Incentivos Fiscais", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.4.03", nome: "Reserva Estatutária", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.4.04", nome: "Reserva para Expansão", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.4.05", nome: "Reserva de Lucros a Realizar", nivel: 3, grupo: "Patrimônio Líquido", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "3.5", nome: "(-) Ações em Tesouraria", nivel: 2, grupo: "Patrimônio Líquido", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "3.6", nome: "(-) Prejuízos Acumulados", nivel: 2, grupo: "Patrimônio Líquido", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "3.9", nome: "Resultado do Exercício", nivel: 2, grupo: "Patrimônio Líquido", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4", nome: "RECEITAS", nivel: 1, grupo: "Receitas", tipo: "Grupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "4.1", nome: "RECEITAS OPERACIONAIS", nivel: 2, grupo: "Receitas", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "4.1.1", nome: "Receita Bruta de Vendas", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: false },
  { codigo: "4.1.1.01", nome: "Receita de Vendas de Mercadorias", nivel: 4, grupo: "Receitas", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.1.1.02", nome: "Receita de Vendas de Produtos", nivel: 4, grupo: "Receitas", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.1.1.03", nome: "Receita de Prestação de Serviços", nivel: 4, grupo: "Receitas", tipo: "Conta Analítica", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.2", nome: "(-) DEDUÇÕES DA RECEITA", nivel: 2, grupo: "Receitas", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "4.2.01", nome: "ICMS sobre Vendas", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.2.02", nome: "PIS/COFINS sobre Vendas", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.2.03", nome: "ISS sobre Serviços", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.2.04", nome: "Descontos Incondicionais", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.2.05", nome: "Abatimentos", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.3", nome: "RECEITAS FINANCEIRAS", nivel: 2, grupo: "Receitas", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "4.3.01", nome: "Juros Ativos", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.3.02", nome: "Rendimentos de Aplicações Financeiras", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.3.03", nome: "Descontos Obtidos", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.3.04", nome: "Variações Cambiais Ativas", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.4", nome: "OUTRAS RECEITAS", nivel: 2, grupo: "Receitas", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "4.4.01", nome: "Receitas de Aluguéis", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.4.02", nome: "Venda de Sucatas", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.4.03", nome: "Dividendos Recebidos", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.4.04", nome: "Ganho na Venda de Imobilizado", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.4.05", nome: "Resultado Positivo da Equivalência Patrimonial", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.5", nome: "Ganhos de Capital", nivel: 2, grupo: "Receitas", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "4.5.01", nome: "Ganho na Venda de Imobilizado", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.6", nome: "Resultado de Investimentos", nivel: 2, grupo: "Receitas", tipo: "Subgrupo", natureza: "Credora", aceitaLancamento: false },
  { codigo: "4.6.01", nome: "Dividendos Recebidos", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "4.6.02", nome: "Resultado Positivo da Equivalência Patrimonial", nivel: 3, grupo: "Receitas", tipo: "Conta Sintética", natureza: "Credora", aceitaLancamento: true },
  { codigo: "5", nome: "DESPESAS", nivel: 1, grupo: "Despesas", tipo: "Grupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "5.1", nome: "Despesas Administrativas", nivel: 2, grupo: "Despesas", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "5.1.01", nome: "Honorários da Diretoria", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.02", nome: "Salários Administrativos", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.03", nome: "Encargos Sociais Administrativos", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.04", nome: "Energia Elétrica", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.05", nome: "Telefone e Internet", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.06", nome: "Serviços de Terceiros", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.07", nome: "Seguros", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.08", nome: "Manutenção e Reparos", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.09", nome: "Material de Escritório", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.10", nome: "Depreciação", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.11", nome: "Amortização", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.1.12", nome: "Exaustão", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.2", nome: "Despesas Comerciais", nivel: 2, grupo: "Despesas", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "5.2.01", nome: "Propaganda e Publicidade", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.2.02", nome: "Comissões sobre Vendas", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.2.03", nome: "Fretes sobre Vendas", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.2.04", nome: "Despesas com Vendas", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.3", nome: "Despesas Financeiras", nivel: 2, grupo: "Despesas", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "5.3.01", nome: "Juros Passivos", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.3.02", nome: "Variações Cambiais Passivas", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.3.03", nome: "Descontos Concedidos", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.4", nome: "Outras Despesas", nivel: 2, grupo: "Despesas", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "5.4.01", nome: "Perdas Diversas", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "5.4.02", nome: "Resultado Negativo da Equivalência Patrimonial", nivel: 3, grupo: "Despesas", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6", nome: "CUSTOS", nivel: 1, grupo: "Custos", tipo: "Grupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "6.1", nome: "Custos de Produção", nivel: 2, grupo: "Custos", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "6.1.01", nome: "Materiais Aplicados", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.1.02", nome: "Salários da Produção", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.1.03", nome: "Encargos Sociais da Produção", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.1.04", nome: "Benefícios a Funcionários", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.1.05", nome: "Energia Elétrica Produção", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.1.06", nome: "Combustíveis e Lubrificantes", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.1.07", nome: "Depreciação da Produção", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.1.08", nome: "Manutenção Industrial", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.2", nome: "Custos das Vendas (CMV / CPV / CSV)", nivel: 2, grupo: "Custos", tipo: "Subgrupo", natureza: "Devedora", aceitaLancamento: false },
  { codigo: "6.2.01", nome: "Custo das Mercadorias Vendidas (CMV)", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.2.02", nome: "Custo dos Produtos Vendidos (CPV)", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "6.2.03", nome: "Custo dos Serviços Vendidos (CSV)", nivel: 3, grupo: "Custos", tipo: "Conta Sintética", natureza: "Devedora", aceitaLancamento: true },
  { codigo: "7", nome: "RESULTADO", nivel: 1, grupo: "Resultado", tipo: "Grupo", natureza: "Variável", aceitaLancamento: false },
  { codigo: "7.1", nome: "Apuração e Encerramento do Resultado", nivel: 2, grupo: "Resultado", tipo: "Subgrupo", natureza: "Variável", aceitaLancamento: false },
  { codigo: "7.1.01", nome: "ARE – Apuração do Resultado do Exercício", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.02", nome: "Encerramento das Receitas", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.03", nome: "Encerramento das Despesas", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.04", nome: "Encerramento dos Custos", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.05", nome: "Resultado Bruto do Exercício", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.06", nome: "Resultado Operacional", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.07", nome: "Resultado Antes do Resultado Financeiro", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.08", nome: "Resultado Antes do IRPJ e da CSLL", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.09", nome: "Resultado Antes das Participações", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.10", nome: "Resultado Líquido do Exercício", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.11", nome: "Lucros Acumulados", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.1.12", nome: "Prejuízos Acumulados", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2", nome: "Tributos sobre o Lucro", nivel: 2, grupo: "Resultado", tipo: "Subgrupo", natureza: "Variável", aceitaLancamento: false },
  { codigo: "7.2.01", nome: "IRPJ sobre o Lucro", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.02", nome: "CSLL sobre o Lucro", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.03", nome: "Provisão para IRPJ", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.04", nome: "Provisão para CSLL", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.05", nome: "IRPJ Corrente", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.06", nome: "CSLL Corrente", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.07", nome: "IRPJ Diferido", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.08", nome: "CSLL Diferida", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.09", nome: "Ajuste de IRPJ do Exercício", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.2.10", nome: "Ajuste de CSLL do Exercício", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.3", nome: "Participações sobre o Resultado", nivel: 2, grupo: "Resultado", tipo: "Subgrupo", natureza: "Variável", aceitaLancamento: false },
  { codigo: "7.3.01", nome: "Participações de Empregados", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.3.02", nome: "Participações de Administradores", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.3.03", nome: "Participações de Debenturistas", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.3.04", nome: "Participações de Partes Beneficiárias", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.3.05", nome: "Fundo de Assistência ou Previdência de Empregados", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.3.06", nome: "Outras Participações sobre o Lucro", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4", nome: "Destinação do Resultado", nivel: 2, grupo: "Resultado", tipo: "Subgrupo", natureza: "Variável", aceitaLancamento: false },
  { codigo: "7.4.01", nome: "Lucros Acumulados", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.02", nome: "Prejuízos Acumulados", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.03", nome: "Reserva Legal", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.04", nome: "Reserva Estatutária", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.05", nome: "Reserva para Contingências", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.06", nome: "Reserva de Incentivos Fiscais", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.07", nome: "Reserva de Lucros a Realizar", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.08", nome: "Reserva para Expansão", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.09", nome: "Dividendos Propostos", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.10", nome: "Dividendos a Distribuir", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.11", nome: "Juros sobre Capital Próprio", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.12", nome: "Reversão de Reservas", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.13", nome: "Absorção de Prejuízos", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.14", nome: "Transferência para Reservas", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.4.15", nome: "Transferência do Lucro para o Patrimônio Líquido", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5", nome: "Ajustes e Complementos do Resultado", nivel: 2, grupo: "Resultado", tipo: "Subgrupo", natureza: "Variável", aceitaLancamento: false },
  { codigo: "7.5.01", nome: "Ajustes de Exercícios Anteriores", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.02", nome: "Reversão de Ajustes de Exercícios Anteriores", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.03", nome: "Ajustes de Avaliação Patrimonial no Resultado", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.04", nome: "Efeitos de Mudança de Critério Contábil", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.05", nome: "Efeitos de Retificação de Erros", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.06", nome: "Ajustes de Encerramento", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.07", nome: "Ajustes Finais de Apuração", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.08", nome: "Reclassificações para Resultado", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.09", nome: "Compensação de Prejuízos do Exercício", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "7.5.10", nome: "Transferência do Resultado para Lucros/Prejuízos Acumulados", nivel: 3, grupo: "Resultado", tipo: "Conta Sintética", natureza: "Variável", aceitaLancamento: true },
  { codigo: "8", nome: "CONTAS DE COMPENSAÇÃO", nivel: 1, grupo: "Contas de Compensação", tipo: "Grupo", natureza: "Compensação", aceitaLancamento: false },
  { codigo: "8.1", nome: "Garantias Prestadas", nivel: 2, grupo: "Contas de Compensação", tipo: "Subgrupo", natureza: "Compensação", aceitaLancamento: true },
  { codigo: "8.2", nome: "Garantias Recebidas", nivel: 2, grupo: "Contas de Compensação", tipo: "Subgrupo", natureza: "Compensação", aceitaLancamento: true },
  { codigo: "8.3", nome: "Bens de Terceiros", nivel: 2, grupo: "Contas de Compensação", tipo: "Subgrupo", natureza: "Compensação", aceitaLancamento: true },
  { codigo: "8.4", nome: "Bens da Empresa em Poder de Terceiros", nivel: 2, grupo: "Contas de Compensação", tipo: "Subgrupo", natureza: "Compensação", aceitaLancamento: true },
  { codigo: "8.5", nome: "Contratos", nivel: 2, grupo: "Contas de Compensação", tipo: "Subgrupo", natureza: "Compensação", aceitaLancamento: true },
  { codigo: "8.6", nome: "Responsabilidades Eventuais", nivel: 2, grupo: "Contas de Compensação", tipo: "Subgrupo", natureza: "Compensação", aceitaLancamento: true },
];

export const LEAVES = CONTAS.filter((c) => c.aceitaLancamento);

export const CONTA_BY_CODE = {};
CONTAS.forEach((c) => { CONTA_BY_CODE[c.codigo] = c; });

export const GRUPOS = [
  "Ativo", "Passivo", "Patrimônio Líquido", "Receitas", "Despesas", "Custos",
  "Resultado", "Contas de Compensação",
];
